function K = GeneraKalman (x_ini,C_ini,Q_ini,R_ini,D,H)

	m = size(x_ini,1);
	n = size(R_ini,1);
   x = x_ini;
   H  = H;
   C = C_ini;
   Q = Q_ini;
   R = R_ini;
   x_pred = x_ini;
   C_pred = C_ini;
   
K = struct( ...
	'm', m, ...
	'n', n, ...
   'x', x, ...
   'x_pred',x_pred, ...
   'D', D, ...
   'H', H, ...
   'C', C, ...
   'C_pred', C_pred, ...
   'Q', Q, ...
   'R', R, ...
   'G', zeros(m,n));